[versions]
# Jetpack compose
activity-compose = "1.12.2"
compose-bom = "2025.12.01"
material-icons = "1.7.8"
material3 = "1.5.0-alpha10"

lifecycle-navigation3 = "2.10.0"
navigation3 = "1.1.0-alpha01"

# Apache POI
apache-poi = "5.5.1"

#Calendar
calendar = "2.9.0"

# Compose Unstyled
composeunstyled = "1.49.6"

# JetLime
jetlime = "4.1.1"

# Lottie Files
lottie-compose = "6.7.1"

# ML Kit
ml-kit = "17.3.0"

# KotStep
kot-step = "3.1.0" 

# Firebase
firebase-bom = "34.3.0"

# Kotlin
core-ktx = "1.17.0"

# PDF Viewer
pdfviewer = "1.1.5-alpha01"

# Hilt
hilt = "2.57.2"
hilt-compiler = "1.3.0"
hilt-compose = "1.3.0"
hilt-work = "1.3.0"

# Other
coil = "3.3.0"
datastore = "1.3.0-alpha03"
data-table = "0.12.0"
material-kolor = "5.0.0-alpha04"
tabler = "3.33.0"
work-ktx = "2.11.0"

# Plugins
android-application = "8.13.0"
compose-plugin = "2.1.20"
google-services = "4.4.3"
ksp = "2.1.20-2.0.1"
kotlin-android = "2.1.20"
kotlin-json = "1.9.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-json" }

activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
material-icons = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "material-icons" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }

lifecycle-viewmodel-navigation3 = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "lifecycle-navigation3" }
navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "navigation3" }
navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3" }

# Apache POI
apache-poi = { group = "org.apache.poi", name = "poi", version.ref = "apache-poi" }
apache-poi-ooxml = { group = "org.apache.poi", name = "poi-ooxml", version.ref = "apache-poi" }

# Calendar
calendar-compose = { group = "com.kizitonwose.calendar", name = "compose", version.ref = "calendar" }

# Compose Unstyled
composeunstyled-primitives = { group = "com.composables", name = "composeunstyled-primitives", version.ref = "composeunstyled" }

# Lottie Files
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie-compose" }

# ML Kit
barcode-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "ml-kit" }

# KotStep
kot-step = { group = "com.github.binayshaw7777", name = "KotStep", version.ref = "kot-step" }

# JetLime
jetlime = { group = "io.github.pushpalroy", name = "jetlime", version.ref ="jetlime" }

pdfviewer = { group = "com.github.bhuvaneshw.pdfviewer", name = "compose", version.ref = "pdfviewer" }
pdfviewer-ui = { group = "com.github.bhuvaneshw.pdfviewer", name = "compose-ui", version.ref = "pdfviewer" }

coil3-compose = { group = "io.coil-kt.coil3", name ="coil-compose", version.ref = "coil" }
coil3-network-okhttp = { group = "io.coil-kt.coil3", name ="coil-network-okhttp", version.ref = "coil" }
coil3-svg = { group = "io.coil-kt.coil3", name ="coil-svg", version.ref = "coil" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore"}
data-table = { group = "com.seanproctor", name = "datatable-material3", version.ref = "data-table" }
material-kolor = { group = "com.materialkolor", name = "material-kolor", version.ref = "material-kolor" }
tabler-icons = { group = "com.woowla.compose.icon.collections", name = "tabler", version.ref = "tabler" }
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-ktx" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage" }

dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-compose" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt-compiler" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt-work" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-application" }
compose-plugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "compose-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-android"}
google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services"}